cyrusfirheir/twee3-language-tools

README.md
src/extension.ts
src/sugarcube-2/macros.ts
src/tree-view.ts

This pull-request adds a `description` field to the macro definitions in the definition files.
Then it also adds a 'hover' for macros (currently only for SugarCube2), which will display any existing description (which supports Markdown).
This would allow embedding documentation/quick-examples and, well, descriptions of what the macro is meant for. Useful for not having to look at the main documentation, and also useful when you're working on a file with others who may add their own widgets/macros.
I initially ran into some issues with determining the macro-name under the cursor, but used `collect` to acquire a list of macros and finding the entry that intersected the current position.
I imagine a more efficient implementation of collect for finding a single macro that intersects with a …

Add macro description; Add macro hover which shows description

---

package.json
src/diagnostics.ts
src/sugarcube-2/arguments.ts
src/sugarcube-2/macros.json
src/sugarcube-2/macros.ts

This pull request adds macro argument parsing for the SugarCube2 format.  
Much of the parsing code is copied (with modifications) from SugarCube2 to provide accurate parsing and errors (as well as not having to implement it all).  
When it encounters an error in syntax it adds it to the editor through diagnostics, making it easier to locate where the issue is.
After this is likely the macroList caching (relatively simple) and the Argument-type validation (not too awful).
Note: There are some macros that set themselves as `skipArgs: true` in the SugarCube code, but seem to do that for performance reasons as they don't use the arguments. Ex: `nobr`, `silently`, etc. Those have been currently set to `skipArgs`, but would be better fit for the argument-type validation PR I plan on making …

Add a lot of Argument parsing code

---

README.md
docs/parameters.md
package.json
src/sugarcube-2/arguments.ts
src/sugarcube-2/macros.json
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts

This pull request adds *Parameter Validation*.  
Summary: Parameter Validation is the ability to specify the format that macros can take their arguments in, and checking against that in the editor. This provides further error-checking (on-top of the Argument Parsing), making so even less manual checking of built passages and branches of code has to be done by the user of the extension.
It does this through a simple string format, with a number of features. The user documentation lies in the new docs folder, `/docs/parameters.md` (no clue how to link a file that is part of the PR before I even commit it).  
As explained in the document, there are a number of parameter types and operators for usage. This allows representing a sizable portion of the non-`skipArgs` macros.  
In the files, …

Parameter types

---

src/extension.ts
src/sugarcube-2/arguments.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts

This PR helps with issue #14 and performs the idea for caching mentioned in PR #15.  
This implements caching for argument parsing results (the parsed arguments, errors, and warnings), and for parameter validation results (the errors, warnings, and the variant).  
With this, it no longer parses and validates macro parameters in the current file every time the user interacts with the document (aka when `diagnostics` is called).  
The cache stores the entries by their argument strings (per macro, so there is no cross-macro caching), which should be efficient due to v8 being Good-At-That(tm). (See: https://v8.dev/blog/hash-code for fun reading). This is done rather than hashing it ourselves because that would require finding a good hash implementation (of which I am not experienced at) for …

Cache Argument-Parsing and Parameter-Validation

---

package.json
src/diagnostics.ts
src/extension.ts
src/sugarcube-2/LICENSE
src/sugarcube-2/arguments.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts
src/sugarcube-2/validation.ts

This pull-request validates passages used in these places:
- Argument links/images.  
- Parameters that take passage names. (Such as `<<link text passage>><</link>>`)  
This does *not* cover normal in-text links, only handling those passed in through arguments to a macro.  
This is a Warning rather than an error because having incomplete paths through a story is not uncommon, and thus is intended at times.  
The images showcases where it currently succeeds at.  
You may notice the `window.garbage` and the `[[garbage]]` link part. This is a necessary false-positive for the common use-case. Since the input to the link can be arbitrary TwineScript (thus translated to JavaScript..), we can not 100% validate whether or not it is meant to be a passage name or a TwineScript string. (We *can* …

Arguments/Parameters Passage Validity Checking

---

src/extension.ts
src/sugarcube-2/code-actions.ts
src/sugarcube-2/macros.ts

This pull-request performs two optimizations for `collect`. It was worked on @Goctionni and myself.
- Caching: The first commit does some basic caching for files. Using their path as the cache key. Uses `vscode.TextDocument`'s `version` field to keep track if it should update. This isn't the most efficient it could be, as this will do a full `collect` whenever the document is updated even a minor amount. So now it will only collect a file once rather than everytime you even click on it.
- The third commit makes this store the promise rather than the result. This stops multiple calls from event listeners from occurring and causing multiple evaluations before the first cache. This could be applied to the `macroList` cache as well, since it had that issue, but the main cause of that was …

Cache collect; Collect performance improvements

---

src/sugarcube-2/macros.json
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts

This switches to using arrays for parameter variants instead of keys.  
This lets us rely on order (which is actually useful) more than objects do, as well as making it easier to manipulate.  
They did not (and would not in the future) provide much utility to give them names, and so can simply be removed.

Switch to using arrays for parameter variants

---

src/sugarcube-2/parameters.ts

The modified isEmpty check was messed up (oops), which would break using an empty parameters list (it wouldn't warn you that you used arguments when it doesn't accept any). This fixed that.

Fix the isEmpty check

---

src/sugarcube-2/arguments.ts

A slight bug from #17  was that it handled image links as if they were passage names, giving a warning on them.  
This changes that to handle them appropriately (ignoring them).
Note: There is actually a case where the image source as handled as a passage, as mentioned in the comment that was added, Twine 1.4 apparently had some weird image passage feature or something. So, that could be handled in the future, but is likely not used that often.

Removes handling of image link as a passage name

---

src/sugarcube-2/macros.ts

This is a fix for collecting multiline macros.
Previously, it uses the matched macros length to calculate the ending character position, but since vscode separates that based on lines, it would be very incorrect for multiple line macros (Accumulating the previous line lengths, then having that as the ending position off into nowhere).
This fixes that.
Note: This shows that there is a slight issue in argument/parameters errors and warnings not taking into account multiple lines. I have ideas for handling that, and it should not be too challenging, but is not in this PR.

Fix multiline macro collection

---

src/sugarcube-2/parameters.ts

This makes so AndNext won't change that it was not found, which means that MaybeNext can properly handle it failing.  
Closes #42

Make AndNext not change that it was not found

---

docs/parameters.md

Removes old example that only made sense in early development version of parameter parsing.

Remove incorrect example

---

package.json
src/extension.ts
src/sugarcube-2/code-actions.ts

Adds a command to quickly grab all unrecognized macros (from files that have diagnostics, so it could be limited by some scanning limitation, but that seems fine) and add them to the definitions. This helps in making the extension easier to use when using it on an existing codebase.

Add Command to add all unrecognized macros to definitions

---

docs/parameters.md

Some of this was outdated, not having been updated to the change which moved from named parameters to array parameters.  
As well, there are some minor improvements.

Fix and improve parameters documentation

---

docs/parameters.md
src/sugarcube-2/macros.json
src/sugarcube-2/parameters.ts

Closes #63 
This adds a new parameter type named `receiver` for macros that take in a variable by name, specifically a sugarcube variable of the form `$name` or `_name`. As well, it makes several macros use this type instead, given that their implementation would error at runtime (ex: https://github.com/tmedwards/sugarcube-2/blob/master/src/macros/macrolib.js#L1685 ) if it was not a valid variable.  
This only detects invalid string literals, as in the above, where you miss the sigil.
Currently this does not supply a quick-fix, since it is a simple fix.
It would be nice to detect the usage of `$name` there, since that is likely a common mistake, but that could also be holding the name of a variable in a variable, which is certainly done in various projects. I might add an off-by-default …

Add receiver parameter type

---

package.json
src/extension.ts
src/formatting.ts

This adds a default keybind (which users can unbind/rebind through VSCode's inbuilt keyboard shortcut handling) to add the appropriate symbols surrounding their words. Currently it has support for SugarCube and Harlowe, but adding others should be easy.
There is potential for improvement in allowing the user to configure what symbol to use, since SugarCube allows the usage of html and they might want `<i>text</i>` instead, and Harlowe supports multiple syntaxes for italics/bold.  
This can also probably be expanded to a keybind for strikethrough and underline, but there is likely less need for such.  
The majority of the code that handles this is from https://github.com/yzhang-gh/vscode-markdown/blob/2043c1b99541e4cc5734c6fc88714865d11a161a/src/formatting.ts#L308 which already handles a …

Add support with keybind for toggling bold/italics in SugarCube and Harlowe

---

README.md
package.json
src/decorations.ts
src/extension.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/validation.ts

This lets users declare decorations in the form of https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions for usage on macros. This is useful in providing visual distinctions for certain macros, such as for dialogue macros and the like.  
By default this is off, since most users will not use it.  
This does not provide any decorations for the standard macros, since they are very personal preference.

Add the ability to declare decorations for macros

---

package.json

Makes the Ctrl+I and Ctrl+B keybinds for bold and italics specific to story formats in the package.json. This makes so that other keybindings will still work in other files in the same project (such as javascript or markdown).  
This duplicates them because currently the when clauses https://code.visualstudio.com/api/references/when-clause-contexts#conditional-operators don't allow parentheses and so representing it in one entry is probably not possible (unless their binding of operators is weird).

Make italics/bold specific to formats to better work when in projects with more than just Twee

---

src/sugarcube-2/macros.json

Nice.
Updated description and parameters for `widget` macro.
[Widget Reference 1](https://github.com/tmedwards/sugarcube-2/commit/5b7d5d34af50ca4c050ab5bc42984eb2874cee71#diff-039b561d03f22e2f8db854a9c9ffa55e459220deef2fe83bbe766baea7abf768),  [Widget Reference 2](https://github.com/tmedwards/sugarcube-2/commit/fe7570f7b5957ecd393d6b87143d7f0e76e9fb4e#diff-039b561d03f22e2f8db854a9c9ffa55e459220deef2fe83bbe766baea7abf768)
Updated description and parameters for `cycle` macro.
[Cycle Reference](https://github.com/tmedwards/sugarcube-2/commit/9a077142451c6bf4354f4d10e926b29c7442aac7#diff-039b561d03f22e2f8db854a9c9ffa55e459220deef2fe83bbe766baea7abf768)
Updated descriptions for `link` and `button` macros.
[Reference](https://github.com/tmedwards/sugarcube-2/commit/e977bdbae5ffc438979917aba25294 …

Updates related to SugarCube 2.36.x

---

package.json
src/extension.ts
src/sugarcube-2/code-actions.ts
src/sugarcube-2/macros.ts

This does a few things.
- Fixes `updateDecorations` code which wasn't guarding against `undefined` properly, so it'd spit out errors.
- Add a command to add all unrecognized macros in the current file. Helpful in large projects, where adding all at once is rather slow, or you only care about the current file.
- Improves the existing 'add all unrecognized macros' command to have a progress bar which informs the user of what it is doing, and allows cancelling it if it is taking too long. Especially helpful in large projects where that might take a while.

Fix bug; Improve adding all macros in files

---

README.md
package.json
src/sugarcube-2/macros.json
src/sugarcube-2/macros.ts
src/sugarcube-2/validation.ts

This adds the ability to specify the `max` number of variants that a child-macro can appear in a macro, such as `<<else>>` having a maximum of `1` per `<<if>>` macro.  
Usage in definitions is by specifying an object instead of a string:  
```json
children: ["elseif", {
"name": "else",
"max": 1
}]
```
Closes #85 
This could be slightly improved by making it place the diagnostic on the offending child-macros, but I decided not to bother.

Add basic max check for validating children macros such as else

---

package.json
story-map/src/App.vue
story-map/src/components/Sidebar.vue

remove some whitespace here, fix a bug on firefox there.
if the scroll change on the story map has consequences im not aware of please ignore it.
btw, loving your extension as a way to restore some of the twine functionality to the twee environment

tiny changes

---

package.json
src/extension.ts
src/story-map/socket.ts
story-map/src/App.vue
story-map/src/SaveToFileDialog/SaveToFile.vue

Added a command to open the passage under the cursor on the story map to complement the open in VS Code feature of the map.
Please let me know if I've done anything strange here, this is the first extension development I've encountered.

Add focus passage in map command

---

src/sugarcube-2/parameters.ts

This adds a `var` parameter type which allows specifying that it expects a literal variable as an argument. This is useful in some narrow applications.

Add var parameter type

---

package-lock.json
package.json
src/sugarcube-2/configuration.ts
src/sugarcube-2/macros.ts

- Bumped minimum vscode types to 1.67 (last version supported by TS 3.9)
- Added baseUri property to macro descriptions (converting them to MarkdownString in the process) so Hover parses relative paths
```yaml
description: "![Test img](./img/various/test.png)"
```
will now evaluate relative to the location of the definition file.
Implements #137

Add relative path evaluation in macro md descriptions

---

package-lock.json
package.json
src/extension.ts
src/parse-text.ts
src/sugarcube-2/configuration.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts
src/sugarcube-2/validation.ts
src/twee-project.ts

Performance changes:
- lastMacroCache is now invalidated using lodash after parameter comparison. This was on the order of 1000x faster in worst case scenarios (~4000 macros)
- Initial passage collection and parsing now runs asynchronously. This was on the order of 10x faster in worst case scenarios. (~500 files/ 10k passages)
- parseConfiguration now runs asynchronously. Each additional configuration file now introduces minimal  performance impact
Function changes:
- `changeStoryFormat` return type changed from `Promise<void>` to `Promise<vscode.TextDocument>`
- `yamlParse` made into separate function for easier error management and future language specific handling. `configuration.ts:115`
- `parseRawText` and `parseText` now accept an extra optional parameter that bypasses updating …

Performance improvements for large projects

---

README.md
docs/enums.md
package-lock.json
package.json
src/extension.ts
src/parse-text.ts
src/sugarcube-2/configuration.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts
src/sugarcube-2/validation.ts
src/twee-project.ts

Relies on commit from #140. Merge that first.
Features:
- Add enum support and documentation to sugarcube macro definitions files
Function changes:
- `onUpdateMacroCache` and `parseMacroParameters` now expect extra parameter providing up-to-date Record of enums
- parseEnums function added `macros.ts:147`

Add Enums to sc2 macro definitions

---

README.md
docs/enums.md
package-lock.json
package.json
src/extension.ts
src/parse-text.ts
src/sugarcube-2/configuration.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts
src/sugarcube-2/validation.ts
src/twee-project.ts

Relies on #140 and #141
Merge those first
Adds user setting to customize number of aliases allowed in a single yaml file before the parser cuts it off from fear of a resource exhaustion attack.

Alias config

---

README.md
docs/enums.md
package-lock.json
package.json
src/extension.ts
src/parse-text.ts
src/sugarcube-2/configuration.ts
src/sugarcube-2/macros.ts
src/sugarcube-2/parameters.ts
src/sugarcube-2/validation.ts
src/twee-project.ts

If a macro name is not provided, the name will now be inferred by the configuration's key.
This fixes an issue where all unnamed macros were receiving the same decoration.

Make sc2 macro names actually optional like documentation says

---

src/sugarcube-2/macros.ts

- Infinite loop in updateDecorations
- Definitions for widgets were jumping 1 line too far

Fix infinite loop in decoration updating

---

src/extension.ts
src/status-bar.ts

Added a new status bar element to display word count. For non-SugarCube projects, the word count is calculated generically (1:1 with Tweego), providing a simple total. However, for SugarCube-based projects, the word count is more accurate.

Word counter patch

---

src/extension.ts
src/parse-text.ts
src/status-bar.ts

Adds:
- Word and passage counter now displays number with locale aware thousands separator
Changes:
- Word and macro word counts are cached in passage meta object
- Word counts are done when each individual file is parsed
Fixes:
- Diagnostics not being updated on initial load
- Saving a file would cause every file to be reparsed
- Parse text could not safely be done before story format was set

Improves performance in large projects and fixes various bugs
